swagger: "2.0"
info:
  title: API Package
  description: API for managing projects
host: localhost:8080
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /project:
    post:
      summary: Insert a project
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: project
          description: Project object
          required: true
          schema:
            $ref: "#/definitions/Project"
      responses:
        '200':
          description: Insert successful
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /project/{id}:
    get:
      summary: Get project by ID
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          type: integer
          format: int64
          required: true
      responses:
        '200':
          description: Success
          schema:
            $ref: "#/definitions/Project"
        '404':
          description: Project not found
        '500':
          description: Internal Server Error
    put:
      summary: Update project
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          type: integer
          format: int64
          required: true
        - in: body
          name: project
          description: Project object
          required: true
          schema:
            $ref: "#/definitions/Project"
      responses:
        '200':
          description: Update successful
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
    delete:
      summary: Delete project
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          type: integer
          format: int64
          required: true
      responses:
        '200':
          description: Delete successful
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /upload/{id}:
    post:
      summary: Upload CSV file
      consumes:
        - multipart/form-data
      produces:
        - text/plain
      parameters:
        - in: path
          name: id
          type: integer
          format: int64
          required: true
        - in: formData
          name: file
          type: file
          description: CSV file to upload
          required: true
      responses:
        '200':
          description: CSV file uploaded and saved to the database successfully!
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
definitions:
  Project:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
      date:
        type: string
        format: date
      sapnumber:
        type: string
      notes:
        type: string
      branchId:
        type: integer
        format: int64
      statusId:
        type: integer
        format: int64
      serviceId:
        type: integer
        format: int64
      service:
        $ref: "#/definitions/Service"
  Service:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
